### ISSUE TITLE
Add your library to jcenter

### ISSUE THREAD

**Issue by nasahapps** [Workday/postman#11]
like every other Android library out there.

**Comment by ndtaylor** [comment]
I actually meant to do this originally, and I ended up giving up and just uploading directly to maven central because the tools to upload to bintray don't actually work if you want to sign your artifacts locally (it always misses the pom.xml). 

I suppose I could have the upload-to-bintray task depend on the upload-to-maven-central task, and then it would pick up the signed pom.xml. It's a little weird, but not the worst thing in world. 

@nasahapps, I'm curious, why do you want the library in jcenter? As I understand it, jcenter includes maven central.

**Comment by nasahapps** [comment]
Jcenter is a better alternative to maven central. Google about it.

And if it was part of maven central, I could just be able to have
`jcenter()` in my build.gradle repositories and download your library but
it failed because it can't find it on jcenter, so I have to instead include
`mavencentral()`, yours (at least in my projects) being the only third
party library that requires this.
