### ISSUE TITLE
Package not included in Android?

### ISSUE THREAD

**Issue by KennethNickles** [Workday/postman#22]
```
../../../../../../.gradle/caches/modules-2/files-2.1/com.workday/postman/1.1/ee8f2b1ed06368a16d962ee20e5ab4ae6c8dc3ec/postman-1.1.jar: Invalid package reference in library; not included in Android: javax.tools. Referenced from com.workday.postman.codegen.ParcelerGenerator.
```

Priority: 6 / 10
Category: Correctness
Severity: Error
Explanation: Package not included in Android.

**Comment by ndtaylor** [comment]
I'm guessing this is a lint error. You can safely ignore this for anything in `com.workday.codegen` because that code will never run in your app. It is only run during compile time.

However, I would recommend using the apt or kapt plugin. There's a note on how to use them in the [readme](https://github.com/Workday/postman#how-to-use-postman).

**Comment by KennethNickles** [comment]
Using apt seem to have fixed.
